version: "3.7"

services:
  sap:
    image: 244249143763.dkr.ecr.us-west-2.amazonaws.com/protect-integration-hybris-runner
    ports:
      - 9002:9002
    networks:
      - protect
    volumes:
      # Map local.properties
      - "${LUDDITES_SRC}/docker-tools/sap/local.properties:/hybris/hybris/config/local.properties"
