version: "3.7"

services:
  protect-client:
    build:
      dockerfile: ../Dockerfile
      context: ${LUDDITES_SRC}/docker-tools/protect-client/build-context
    environment:
      NPM_TOKEN: ${NPM_TOKEN:-}
      PROTECT_API_URL: ${PROTECT_API_URL}
    networks:
      - protect
    volumes:
      - "~/.npmrc/:/home/node/.npmrc:ro"
      - "${LUDDITES_SRC}/luddites-client:/home/node/luddites-client"
    ports:
      - "53000:3000"
      - "54000:4000"

  ngrok-protect-client:
    depends_on:
      - protect-client
    environment:
      NGROK_AUTH: "${NGROK_AUTH}"
      NGROK_SUBDOMAIN: "${PROTECT_CLIENT_SUBDOMAIN}"
      NGROK_PORT: "protect-client:3000"
      NGROK_HEADER: "localhost"
    image: wernight/ngrok
    networks:
      - protect
    ports:
      - "40400:4040"
