version: "3.7"

services:
  mysql:
    command:
      [
        "mysqld",
        "--character-set-server=utf8",
        "--collation-server=utf8_general_ci",
      ]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    image: mysql:5.6
    networks:
      - protect
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"

volumes:
  mysql-data: {}
