version: "3.7"

services:
  pgadmin:
    depends_on: 
      - postgres
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - "pgadmin-data:/root/.pgadmin"
    ports:
      - "15480:80"
    networks:
      - protect
    restart: unless-stopped

volumes:
  pgadmin-data: {}
