version: "3.7"

services:
  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-protect}
      POSTGRES_USERNAME: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    # This version should match the version compatible w/ Aurora serverless
    image: postgres:10.7
    networks:
      - protect
    ports:
      - "15432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

volumes:
  postgres-data: {}
