version: "3.7"

services:
  template-service:
    build:
      dockerfile: ../Dockerfile
      context: ${LUDDITES_SRC}/docker-tools/template-service/build-context
    environment:
      PROTECT_API_URL: ${PROTECT_API_URL}
      PROXY_BASE: "https://${TEMPLATE_SERVICE_SUBDOMAIN}.ngrok.io/proxy"
    networks:
      - protect
    volumes:
      - "~/.npmrc/:/home/node/.npmrc:ro"
      - "${LUDDITES_SRC}/luddites-template-service:/home/node/luddites-template-service"

  ngrok-template-service:
    depends_on:
      - template-service
    environment:
      NGROK_AUTH: "${NGROK_AUTH}"
      NGROK_SUBDOMAIN: "${TEMPLATE_SERVICE_SUBDOMAIN}"
      NGROK_PORT: "template-service:4040"
      NGROK_HEADER: "localhost"
    image: wernight/ngrok
    networks:
      - protect
    ports:
      - "40402:4040"
