version: "3.7"

services:
  magento:
    build:
      dockerfile: ../Dockerfile
      context: ./build-context
    depends_on:
      - mysql
    environment:
      # This variable must match the mount location below in `volumes`
      # and be a subdirectory of `/var/www/html` to make apache happy
      MODULE_SRC: "/var/www/html/protect-integration-module"
    networks:
      - protect
    sysctls:
      # Needed for non-root APACHE_RUN_USER when binding to port 80
      net.ipv4.ip_unprivileged_port_start: 0
    volumes:
      # Map the module source so that changes made on the host are seen inside the container
      - "${NS8_SRC}/protect-integration-magento/:/var/www/html/protect-integration-module"
      # Map the .env file so that changes can take effect without recreating the container
      - "${NS8_SRC}/protect-tools-docker/magento/.env:/etc/environment"

  ngrok-magento:
    depends_on:
      - magento
    environment:
      NGROK_AUTH: "${NGROK_AUTH}"
      NGROK_SUBDOMAIN: "${MAGENTO_NGROK_SUBDOMAIN}"
      NGROK_PORT: "magento:80"
    image: wernight/ngrok
    networks:
      - protect
