version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - protect
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
      - "${NS8_SRC}/protect-tools-docker/v1-api-service/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PWD}"
      MONGO_INITDB_DATABASE: administration

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - protect
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PWD}"

volumes:
  mongodbdata: {}
